spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

resilience4j:
  ratelimiter:
    configs:
      default:
        register-health-indicator: true
        timeout-duration: 0
    instances:
      authorRateLimiter:
        base-config: default
        limit-for-period: 100
        limit-refresh-period: 60s
      genreRateLimiter:
        base-config: default
        limit-for-period: 5
        limit-refresh-period: 60s
      bookRateLimiter:
        base-config: default
        limit-for-period: 100
        limit-refresh-period: 60s
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 2s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 3
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - java.sql.SQLException
          - org.hibernate.exception.JDBCConnectionException
          - java.net.ConnectException
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
          - ru.otus.hw.exceptions.EntityNotFoundException
    instances:
      dbBreaker:
        base-config: default
        sliding-window-size: 20
        failure-rate-threshold: 10
        wait-duration-in-open-state: 30s
        slow-call-rate-threshold: 10
        slow-call-duration-threshold: 1ms
