server:
  port: 8081
spring:
  kafka:
    security:
      protocol: PLAINTEXT
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: bank
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      properties:
        spring:
            json:
              use:
                type:
                  headers: false
              trusted:
                packages: "*"
              value:
                default:
                  type: ru.otus.hw.kafka.dto.PaymentReq
  datasource:
    url: jdbc:h2:mem:maindb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
logging:
  config: classpath:logback-spring.xml
